#!/bin/bash
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -ak|--app-key)
    APP_KEY="$2"
    shift
    shift
    ;;
    -sz|--service-zone)
    SERVICE_ZONE="$2"
    shift
    shift
    ;;
    *)
esac
done

if [ -z ${SERVICE_ZONE} ] ; then
    SERVICEZONE="real"
fi

echo "APPKEY = ${APP_KEY}"
echo "SERVICEZONE = ${SERVICE_ZONE}"

if [ -z ${APP_KEY} ] ; then
    echo "Please input appkey."
    exit 0
fi

#Dev Test
COMMAND_PATH="${PROJECT_DIR}/../Pods/ToastLogger/toastcloud.sdk-*/SymbolUploader "

#Release
#COMMAND_PATH="${PODS_ROOT}/ToastLogger/toastcloud.sdk-*/SymbolUploader "

ARGUMENTS="--app-key ${APP_KEY} --project-version ${MARKETING_VERSION}  --service-zone ${SERVICE_ZONE} ${TARGET_BUILD_DIR}"

eval $COMMAND_PATH$ARGUMENTS
